### ISSUE TITLE
Parameters mismatch Typescript definitions

### ISSUE THREAD

**Issue by DaveStein** [howardabrams/node-mocks-http#245]
Just found your repo over here: https://stackoverflow.com/questions/62230808/test-nextjs-api-middleware-with-jest

I did `httpMocks.createRequest<NextApiRequest>();` and `httpMocks.createResponse<NextApiRequest>();` but TS complains. Does this repo need an update or am I doing something wrong? I'm currently on Next `11.0.1`

```
Type 'NextApiRequest' does not satisfy the constraint 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
  Type 'NextApiRequest' is missing the following properties from type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>': get, header, accepts, acceptsCharsets, and 30 more.
```

```
Type 'NextApiResponse<any>' does not satisfy the constraint 'Response<any, Record<string, any>>'.
  Type 'ServerResponse & { send: Send<any>; json: Send<any>; status: (statusCode: number) => NextApiResponse<any>; redirect(url: string): NextApiResponse<...>; redirect(status: number, url: string): NextApiResponse<...>; setPreviewData: (data: string | object, options?: { ...; } | undefined) => NextApiResponse<...>; clearPr...' is missing the following properties from type 'Response<any, Record<string, any>>': sendStatus, links, jsonp, sendFile, and 18 more.
```

**Comment by DaveStein** [comment]
PS: I just realized Next11 is only a couple weeks old

**Comment by doshii-mo** [comment]
> PS: I just realized Next11 is only a couple weeks old

I get the same on 10.2.3

**Comment by doshii-mo** [comment]
@DaveStein Not sure if you've got `auth0` package installed? I notice I only get this if I install that package. If I remove it, it goes away.

**Comment by DaveStein** [comment]
I don't have `auth0` anywhere in my `package-lock.json` so maybe it's some dependency of that we both have?

**Comment by pmazumder3927** [comment]
I'm having this issue as well. Removing `@auth0/nextjs` didn't fix it for me.

**Comment by fillon** [comment]
same here

**Comment by MGough** [comment]
I'm also seeing this issue with `next` 10.2.3 and `node-mocks-http` 1.10.0 (as 1.11.0 is not on the Yarn registry yet).

Has anyone found a way to resolve this issue?

**Comment by ruohola** [comment]
It happened to me when I installed a package that had specified `@types/express` as its dependency. The issue is that both `express.Request` and `NextApiRequest` extend Node's `http.IncomingMessage`, but they are not compatible with each other.

**Comment by ruohola** [comment]
This happened to me when I installed a package that had specified `@types/express` as its dependency. The issue is that both `express.Request` and `NextApiRequest` extend Node's `http.IncomingMessage`, but they are not compatible with each other.

I fixed this like this:

```
import { createMocks as _createMocks } from 'node-mocks-http';
import type { RequestOptions, ResponseOptions } from 'node-mocks-http';

const createMocks = _createMocks as (
  reqOptions?: RequestOptions,
  resOptions?: ResponseOptions,
  // @ts-ignore: Fixing this: https://github.com/howardabrams/node-mocks-http/issues/245
) => Mocks<NextApiRequest, NextApiResponse>;

...

const { req, res } = createMocks({
  method: 'GET',
});

// Check types by hovering:
// const req: MockRequest<NextApiRequest>
// const res: MockResponse<NextApiResponse<any>>
```

**Comment by ruohola** [comment]
Not stale.

**Comment by ruohola** [comment]
Shoulf not be closed.

**Comment by zunkelty** [comment]
I still have this issue in combination with [iron-session](https://github.com/vvo/iron-session). Should not be closed.

**Comment by ruohola** [comment]
Not stale.

**Comment by ruohola** [comment]
This should be reopened.

**Comment by mtoranzoskw** [comment]
For those that are seeing this because they have typing issue, check this out https://github.com/howardabrams/node-mocks-http/issues/255#issuecomment-1136674043 
Typing union is the key.
